name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build app
      run: |
        chmod +x create_app.sh
        chmod +x create_dmg.sh
        ./create_dmg.sh
        
    - name: Create Release with GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "ScreenTextExtractor ${{ github.ref_name }}" \
          --notes "## ScreenTextExtractor ${{ github.ref_name }}
        
        ### インストール方法
        1. \`ScreenTextExtractor-1.0.dmg\` をダウンロード
        2. DMGファイルを開く
        3. ScreenTextExtractor.app を Applications フォルダにドラッグ&ドロップ
        4. アプリケーションから起動
        
        ### 使用方法
        - \`Cmd+Shift+2\` でOCR機能を起動
        - 画面の任意の領域を選択してテキストを抽出
        
        ### システム要件
        - macOS 15.0 (Sequoia) 以降
        - 画面録画権限の許可が必要" \
          ./ScreenTextExtractor-1.0.dmg